enable-magisk-update = false
parallel-jobs = 1

[Music]
build-mode = "apk"
arch = "all"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"

[YouTube]
build-mode = "apk"
arch = "all"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"

[Instagram]
enabled = true
build-mode = "apk"
version = "latest"
arch = "arm64-v8a"
uptodown-dlurl = "https://instagram.en.uptodown.com/android"
apkmirror-dlurl = ""
included-patches = "'Hide ads' 'Hide suggested content' 'Sanitize sharing links' 'Disable signature check'"
exclusive-patches = true

[Crunchyroll]
enabled = true
build-mode = "apk"
version = "latest"
arch = "all"
uptodown-dlurl = "https://crunchyroll.en.uptodown.com/android"
apkmirror-dlurl = ""