name: Upload APKs to Archive.org

on:
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Extract first APK filename as identifier
        id: pkg
        run: |
          file=$(ls apks/*.apk | head -n 1)
          name=$(basename "$file" .apk)
          echo "pkg_name=$name" >> $GITHUB_OUTPUT

      - name: Upload APKs
        uses: palewire/internet-archive-upload@v1
        with:
          access-key: ${{ secrets.IA_ACCESS_KEY }}
          secret-key: ${{ secrets.IA_SECRET_KEY }}
          identifier: ${{ steps.pkg.outputs.pkg_name }}
          files: local-apks/*.apk
